services:
  backend:
    build:
      context: ../src/backend
      dockerfile: ../../docker/Dockerfile-backend
    container_name: filmometer-backend
    volumes:
      - ../src/backend/data:/app/data
    networks:
      - filmnet
    

  frontend:
    build:
      context: ../src/frontend
      dockerfile: ../../docker/Dockerfile-frontend
    container_name: filmometer-frontend
    depends_on:
      - backend
    volumes:
      - ../docker/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - filmnet
    ports:
      - "80:80"  

networks:
  filmnet:
    driver: bridge
