version: "3"

services:
  backend:
    build: ../src/backend
    container_name: filmometer-backend
    volumes:
      - ../src/backend/data:/app/data
    networks:
      - filmnet
    ports:
      - "3001:3000"

  frontend:
    build: ../src/frontend
    container_name: filmometer-frontend
    depends_on:
      - backend
    networks:
      - filmnet
    ports:
      - "8080:80"

networks:
  filmnet:
    driver: bridge

